### ISSUE TITLE
Missing Translation for Translator.

### ISSUE THREAD

**Issue by midorlo** [bytebeats/polyglot#26]
(pun intended)

![descriptive image](https://i.imgur.com/ealT8s0.png)

Non chinese (I suppose) speakers will not be able to go anywhere from here

**Comment by bytebeats** [comment]
@midorlo how about adding a preference for `my mother tongue` on setting page? Or just change these chinese into english?  Or do you have any better ideas?

Meanwhile, thanks for your issues.

**Comment by midorlo** [comment]
A setting would probably be best. One can default to system-language, so you still have cn locale on install for those who use it.

**Comment by bytebeats** [comment]
@midorlo I uploaded a new version of polyglot for verification, thanks for your time!

**Comment by midorlo** [comment]
It's me to thank you! Dealing with vue samples oftenly introduces language barriers. Your addon is a decent help for me :-)
